### ISSUE TITLE
Add local() argument to _fonts.scss

### ISSUE THREAD

**Issue by stephiescastle** [nasa-jpl/explorer-1#59]
As seen in https://github.com/nasa-jpl/www-frontend/pull/1190/files, we should add a `local()` argument to our src attributes in _fonts.scss:

```scss
@font-face {
  font-family: Metropolis;
  font-weight: 800;
  font-style: normal;
  font-display: swap;
  src: local(Metropolis-ExtraBold), local(Metropolis ExtraBold),
   url(../fonts/metropolis/Metropolis-ExtraBold.woff2);
}
...
```

url() is recommended as a fallback
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

> If the local() function is provided, specifying a font name to look for on the user's computer, and the user agent finds a match, that local font is used. Otherwise, the font resource specified using the url() function is downloaded and used.
